version: "3"

services:

  db:
    image: mariadb:10.6
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: airmeet
      MYSQL_USER: root
      MYSQL_PASSWORD: root

  twitter-backend:
    depends_on:
      - db
    image: abhigorecha/airmeet:latest
    ports:
      - "8080:8080"
    restart: always
    environment:
      MYSQL_DB_HOST: db
      MYSQL_DB_PORT: 3306
      MYSQL_DB_UNAME: root
      MYSQL_DB_PASSWD: root

volumes:
  db_data: {}